// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM_O5PKAv1Kcs2vpXNGjU6t3nk2VSEKjw',
    appId: '1:757178833866:web:dabe83fd96c175327f0d33',
    messagingSenderId: '757178833866',
    projectId: 'queuesystem-a3ea1',
    authDomain: 'queuesystem-a3ea1.firebaseapp.com',
    storageBucket: 'queuesystem-a3ea1.firebasestorage.app',
    measurementId: 'G-2J4YFNH8RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvC3n4ZhGYUntvwRlCs30p6MUTqdax6ao',
    appId: '1:757178833866:android:7157884ed7ae3d6d7f0d33',
    messagingSenderId: '757178833866',
    projectId: 'queuesystem-a3ea1',
    storageBucket: 'queuesystem-a3ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9nrdCRxySbo1j1PP1aZHnyWQf0ICJMQ',
    appId: '1:757178833866:ios:064958e47cea2aa17f0d33',
    messagingSenderId: '757178833866',
    projectId: 'queuesystem-a3ea1',
    storageBucket: 'queuesystem-a3ea1.firebasestorage.app',
    iosClientId:
        '757178833866-8bmj9t20afmnde1s4dd5ph522m2v7c6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.taborq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9nrdCRxySbo1j1PP1aZHnyWQf0ICJMQ',
    appId: '1:757178833866:ios:064958e47cea2aa17f0d33',
    messagingSenderId: '757178833866',
    projectId: 'queuesystem-a3ea1',
    storageBucket: 'queuesystem-a3ea1.firebasestorage.app',
    iosClientId:
        '757178833866-8bmj9t20afmnde1s4dd5ph522m2v7c6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.taborq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM_O5PKAv1Kcs2vpXNGjU6t3nk2VSEKjw',
    appId: '1:757178833866:web:719f71f7b142ff127f0d33',
    messagingSenderId: '757178833866',
    projectId: 'queuesystem-a3ea1',
    authDomain: 'queuesystem-a3ea1.firebaseapp.com',
    storageBucket: 'queuesystem-a3ea1.firebasestorage.app',
    measurementId: 'G-LMZ6WJWD9E',
  );
}
